version: '3'

services:
  flaskapi:
    container_name: flaskapi
    restart: always
    build: ./flaskdocker
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000  HelloWorld:app
  
  nginx:
    container_name: nginx
    restart: always
    build: ./Nginx
    ports:
      - "80:80"
    depends_on:
      - flaskapi