version: "3.7"

services:

  flask:
    build: Dockerfile
    container_name: flask
    restart: always
    expose:
      - 8080


  nginx:
    build: ./Nginx
    container_name: nginx-gunicorn
    restart: always
    expose:
      - "80:80"

